site_name: kerbh0lz
markdown_extensions:
  # Python Markdown  
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: 
        - docs
theme:
  name: terminal
  palette: dark
  features:
      # - footer.prev_next
      - navigation.side.hide
      - navigation.side.indexes
      - navigation.side.toc.hide
      # - navigation.top.hide
      # - navigation.top.cursor_animation.hide
      # - navigation.top.search_button.hide
      # - revision.date
      # - revision.history
      # - style.links.underline.hide

nav:
  - audios: 'audio.md'
  - screens: 'screenshots.md'
