name: "Deploy mkdocs to gh-pages"
on:
  push:
    paths: ['mkdocs.yml']
    branches: ['main']
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email datenblatt+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%Y%m%d%H')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-terminal-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-terminal-
      - run: pip install mkdocs
      - run: pip install mkdocs-terminal
      - run: mkdocs gh-deploy --force
